### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by tianqiqiu** [dibo-software/diboot-element-admin#28]
npm ERR! sha1-7gpkyK9ejO6mdoexM3YeG+y9HT0=sha512-b39TBaTSfV6yBrapU89p5fKekE2m/NwnDocOVruQFS1/veMgdzuPcnOM34M6CwxW8jH/lxEa5rBoDeUwu5HHTw== integrity checksum failed when using sha1: wanted sha1-7gpkyK9ejO6mdoexM3YeG+y9HT0=sha512-b39TBaTSfV6yBrapU89p5fKekE2m/NwnDocOVruQFS1/veMgdzuPcnOM34M6CwxW8jH/lxEa5rBoDeUwu5HHTw== but got sha1-7gpkyK9ejO6mdoexM3YeG+y9HT0=. (18921 bytes).Can not install complete,please help me.

**Comment by JerryMa1024** [comment]
node v14.x，用taobao镜像，如果还有问题请加群交流
